'use client';
import {useEffect,useRef,useState} from 'react';
import type {Filter,Restaurant} from '../lib/types';
import {eligible,availableFilters,filters as allFilters,pickOne,recommendThree} from '../lib/recommend';
import {track} from '../lib/analytics';
import {feedbackTags,type Feedback} from '../lib/feedback';
import PlacePhoto from './PlacePhoto';
type Screen='home'|'three'|'result'|'feedback'|'done'|'empty';
const pendingKey='baplah:pending-meal';
export default function LunchApp({restaurants}:{restaurants:Restaurant[]}){
 const [screen,setScreen]=useState<Screen>('home');const [filters,setFilters]=useState<Filter[]>(['Nearby']);
 const [options,setOptions]=useState<Restaurant[]>([]);const [selected,setSelected]=useState<Restaurant|null>(null);
 const [pending,setPending]=useState<Restaurant|null>(null);const [rating,setRating]=useState<Feedback['rating']|null>(null);
 const [tags,setTags]=useState<string[]>([]);const [sending,setSending]=useState(false);const [status,setStatus]=useState('');
 const [mode,setMode]=useState<'one'|'three'>('three');const heading=useRef<HTMLHeadingElement>(null);const initialized=useRef(false);
 const supported=availableFilters(restaurants);const count=eligible(restaurants,filters).length;
 useEffect(()=>{if(initialized.current)return;initialized.current=true;track('home_opened');try{const saved=JSON.parse(localStorage.getItem(pendingKey)??'null');if(saved && Date.now()-saved.at<7*86400000)setPending(restaurants.find(r=>r.id===saved.id)??null);}catch{}},[restaurants]);
 useEffect(()=>{if(screen!=='home')heading.current?.focus();},[screen,selected]);
 function goHome(){setScreen('home');setStatus('');}
 function toggle(f:Filter){setFilters(prev=>prev.includes(f)?prev.filter(x=>x!==f):[...prev,f]);track('filter_selected',{filter:f});}
 function choose(r:Restaurant){setSelected(r);setScreen('result');track('restaurant_selected',{restaurantId:r.id,filters,mode});}
 function three(reroll=false){setMode('three');track(reroll?'reroll_requested':'recommend_3_requested',{filters,mode:'three'});const result=recommendThree(restaurants,filters,reroll?options.map(r=>r.id):[]);setOptions(result);setScreen(result.length===3?'three':'empty');}
 function one(another=false){setMode('one');track(another?'reroll_requested':'just_pick_requested',{filters,mode:'one'});const r=pickOne(restaurants,filters,another&&selected?[selected.id]:[]);if(r){setSelected(r);setScreen('result');track('restaurant_selected',{restaurantId:r.id,filters,mode:'one'});}else setScreen('empty');}
 function maps(){if(!selected)return;track('maps_opened',{restaurantId:selected.id,filters,mode});setPending(selected);try{localStorage.setItem(pendingKey,JSON.stringify({id:selected.id,at:Date.now()}));}catch{} }
 function feedback(r:Restaurant){setSelected(r);setRating(null);setTags([]);setStatus('');setScreen('feedback');}
 async function submit(){if(!selected||!rating||sending)return;setSending(true);const body:Feedback={id:crypto.randomUUID(),restaurantId:selected.id,rating,tags,createdAt:new Date().toISOString()};let local=false;
  try{const old=JSON.parse(localStorage.getItem('baplah:feedback')??'[]');localStorage.setItem('baplah:feedback',JSON.stringify([body,...(Array.isArray(old)?old:[])].slice(0,100)));local=true;}catch{}
  let remote=false;try{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(7000)});if(response.ok)remote=(await response.json()).persisted===true;}catch{}
  setSending(false);if(!local&&!remote){setStatus('Couldn’t save your feedback. Please try again.');return;}
  track('feedback_submitted',{restaurantId:selected.id});setStatus(remote?'Thanks — your feedback has been saved.':'Thanks — saved on this device.');setPending(null);try{localStorage.removeItem(pendingKey);}catch{}setScreen('done');
 }
 const context=(r:Restaurant)=>`${r.cuisine.join(' / ')} · ${r.walkingMinutes!==null?`~${r.walkingMinutes} min walk`:r.area==='MBC'?'Within MBC':r.area==='ARC'?'Alexandra Retail Centre':r.area}`;
 return <main><header><button className="brand" onClick={goHome} aria-label="밥Lah home"><span lang="ko">밥</span>Lah</button>{screen!=='home'&&<button className="back" onClick={goHome}>Change filters</button>}</header>
 {screen==='home'&&<><h1>Eat where today?</h1><p className="muted">Pick a few constraints, or let 밥Lah decide.</p><div className="chips" aria-label="Lunch filters">{allFilters.map(f=><button className="chip" key={f} aria-pressed={filters.includes(f)} disabled={!supported.includes(f)} title={!supported.includes(f)?`${f} is waiting for verified restaurant data`:undefined} onClick={()=>toggle(f)}>{f}</button>)}<button className="chip" aria-pressed={!filters.length} onClick={()=>{setFilters([]);track('filter_selected',{filters:[]});}}>Anything</button></div>{supported.length<4&&<p className="muted small">Quick and Cheap are coming after a little more lunch research.</p>}<button className="action primary" onClick={()=>three()}>Show me 3</button><button className="action" onClick={()=>one()}>Just pick something</button>{pending&&<div className="notice"><p>Been to {pending.name}?</p><button className="back" onClick={()=>feedback(pending)}>How was lunch? →</button></div>}<p className="muted small">For lunch around Mapletree Business City. {restaurants.length} places, including your original list.</p></>}
 {screen==='three'&&<><h2 ref={heading} tabIndex={-1}>Three good options</h2><p className="accent">{filters.join(' · ')||'Anything'}</p>{options.map(r=><button key={r.id} className="card card-photo" onClick={()=>choose(r)}><strong>{r.name}</strong><span className="context">{context(r)}</span><span className="reason">{r.reason}</span>{r.importedFromV1&&<span className="muted small">From your original list · not rechecked</span>}</button>)}<button className="action" onClick={()=>three(true)}>Reroll 3</button><p className="muted small">{count===3?'These are the three places matching your filters. Change filters for more variety.':'A fresh set, whenever you need it.'}</p></>}
 {screen==='result'&&selected&&<><PlacePhoto key={selected.id} id={selected.id} name={selected.name}/><h2 ref={heading} tabIndex={-1}>{selected.name}</h2><p className="muted">{context(selected)}</p><div className="why"><strong>WHY THIS ONE</strong><p>{selected.reason}</p><p className="muted small">{selected.tags.join(' · ')}</p></div><p className="muted small">{selected.address}</p>{selected.importedFromV1&&<p className="notice small">From your original list · not rechecked. Confirm this outlet and its opening hours in Maps before travelling.</p>}<a className="action primary" href={selected.mapUrl} target="_blank" rel="noopener noreferrer" onClick={maps}>LET’S GO · Open Google Maps</a><button className="action" onClick={()=>one(true)}>Pick another</button>{pending?.id===selected.id&&<button className="back" onClick={()=>feedback(selected)}>I’ve eaten here · Leave feedback</button>}<p className="muted small">Check opening hours in Maps before heading out.</p></>}
 {screen==='empty'&&<><h2 ref={heading} tabIndex={-1}>{count?'A smaller lunch list':'No matches this time'}</h2><p className="muted">{count?`Only ${count} ${count===1?'place matches':'places match'} your filters. We need three for a shortlist.`:'Try fewer filters to find a lunch option.'}</p>{count>0&&<button className="action primary" onClick={()=>one()}>Just pick something</button>}<button className="action" onClick={()=>{setFilters([]);goHome();}}>Use Anything</button><button className="back" onClick={goHome}>Change filters</button></>}
 {screen==='feedback'&&selected&&<><h2 ref={heading} tabIndex={-1}>How was lunch?</h2><p className="feedback-question">Would you recommend {selected.name} to colleagues?</p><div className="choices" aria-label="Recommendation rating">{([['yes','👍 Yes, would go again'],['okay','😐 It was okay'],['skip','👎 Probably skip next time']] as const).map(([value,label])=><button key={value} className="action" aria-pressed={rating===value} onClick={()=>setRating(value)}>{label}</button>)}</div><p className="muted">Optional tags</p><div className="chips">{feedbackTags.map(tag=><button className="chip" key={tag} aria-pressed={tags.includes(tag)} onClick={()=>setTags(t=>t.includes(tag)?t.filter(x=>x!==tag):[...t,tag])}>{tag}</button>)}</div><button className="action primary" disabled={!rating||sending} onClick={submit}>{sending?'Saving…':'Save feedback'}</button><button className="back" onClick={goHome}>Maybe later</button>{status&&<p role="alert">{status}</p>}<p className="muted small">Feedback may be saved only on this device during the pilot.</p></>}
 {screen==='done'&&<><h2 ref={heading} tabIndex={-1}>Thanks for the lunch tip.</h2><p className="muted" role="status">{status}</p><button className="action primary" onClick={goHome}>Back to lunch</button></>}
 <footer><a href="/about">About this pilot</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></footer></main>;
}
